/**
 * generated by Xtext 2.25.0
 */
package xtext.factoryLang.shortDSL.shortDSL;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Configuration S</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link xtext.factoryLang.shortDSL.shortDSL.ConfigurationS#getDevices <em>Devices</em>}</li>
 * </ul>
 *
 * @see xtext.factoryLang.shortDSL.shortDSL.ShortDSLPackage#getConfigurationS()
 * @model
 * @generated
 */
public interface ConfigurationS extends EObject
{
  /**
   * Returns the value of the '<em><b>Devices</b></em>' containment reference list.
   * The list contents are of type {@link xtext.factoryLang.shortDSL.shortDSL.DeviceS}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Devices</em>' containment reference list.
   * @see xtext.factoryLang.shortDSL.shortDSL.ShortDSLPackage#getConfigurationS_Devices()
   * @model containment="true"
   * @generated
   */
  EList<DeviceS> getDevices();

} // ConfigurationS
