/**
 * generated by Xtext 2.25.0
 */
package xtext.factoryLang.shortDSL.shortDSL;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Crane Action</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see xtext.factoryLang.shortDSL.shortDSL.ShortDSLPackage#getCraneAction()
 * @model
 * @generated
 */
public interface CraneAction extends CraneActionS
{
} // CraneAction
