/**
 * generated by Xtext 2.25.0
 */
package xtext.factoryLang.shortDSL.shortDSL;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Device Value</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link xtext.factoryLang.shortDSL.shortDSL.DeviceValue#getValue <em>Value</em>}</li>
 *   <li>{@link xtext.factoryLang.shortDSL.shortDSL.DeviceValue#getConfigurationValue <em>Configuration Value</em>}</li>
 * </ul>
 *
 * @see xtext.factoryLang.shortDSL.shortDSL.ShortDSLPackage#getDeviceValue()
 * @model
 * @generated
 */
public interface DeviceValue extends EObject
{
  /**
   * Returns the value of the '<em><b>Value</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Value</em>' containment reference.
   * @see #setValue(EObject)
   * @see xtext.factoryLang.shortDSL.shortDSL.ShortDSLPackage#getDeviceValue_Value()
   * @model containment="true"
   * @generated
   */
  EObject getValue();

  /**
   * Sets the value of the '{@link xtext.factoryLang.shortDSL.shortDSL.DeviceValue#getValue <em>Value</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Value</em>' containment reference.
   * @see #getValue()
   * @generated
   */
  void setValue(EObject value);

  /**
   * Returns the value of the '<em><b>Configuration Value</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Configuration Value</em>' reference.
   * @see #setConfigurationValue(ConfigurationValueS)
   * @see xtext.factoryLang.shortDSL.shortDSL.ShortDSLPackage#getDeviceValue_ConfigurationValue()
   * @model
   * @generated
   */
  ConfigurationValueS getConfigurationValue();

  /**
   * Sets the value of the '{@link xtext.factoryLang.shortDSL.shortDSL.DeviceValue#getConfigurationValue <em>Configuration Value</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Configuration Value</em>' reference.
   * @see #getConfigurationValue()
   * @generated
   */
  void setConfigurationValue(ConfigurationValueS value);

} // DeviceValue
