/**
 * generated by Xtext 2.25.0
 */
package xtext.factoryLang.shortDSL.shortDSL;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Disk Zone Short</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link xtext.factoryLang.shortDSL.shortDSL.DiskZone_Short#getName <em>Name</em>}</li>
 *   <li>{@link xtext.factoryLang.shortDSL.shortDSL.DiskZone_Short#getSlot <em>Slot</em>}</li>
 * </ul>
 *
 * @see xtext.factoryLang.shortDSL.shortDSL.ShortDSLPackage#getDiskZone_Short()
 * @model
 * @generated
 */
public interface DiskZone_Short extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see xtext.factoryLang.shortDSL.shortDSL.ShortDSLPackage#getDiskZone_Short_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link xtext.factoryLang.shortDSL.shortDSL.DiskZone_Short#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Slot</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Slot</em>' attribute.
   * @see #setSlot(int)
   * @see xtext.factoryLang.shortDSL.shortDSL.ShortDSLPackage#getDiskZone_Short_Slot()
   * @model
   * @generated
   */
  int getSlot();

  /**
   * Sets the value of the '{@link xtext.factoryLang.shortDSL.shortDSL.DiskZone_Short#getSlot <em>Slot</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Slot</em>' attribute.
   * @see #getSlot()
   * @generated
   */
  void setSlot(int value);

} // DiskZone_Short
