/**
 * generated by Xtext 2.25.0
 */
package xtext.factoryLang.shortDSL.shortDSL;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Local Variable</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see xtext.factoryLang.shortDSL.shortDSL.ShortDSLPackage#getLocalVariable()
 * @model
 * @generated
 */
public interface LocalVariable extends VariableS
{
} // LocalVariable
