/**
 * generated by Xtext 2.25.0
 */
package xtext.factoryLang.shortDSL.shortDSL;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see xtext.factoryLang.shortDSL.shortDSL.ShortDSLFactory
 * @model kind="package"
 * @generated
 */
public interface ShortDSLPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "shortDSL";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.factoryLang.xtext/shortDSL/ShortDSL";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "shortDSL";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  ShortDSLPackage eINSTANCE = xtext.factoryLang.shortDSL.shortDSL.impl.ShortDSLPackageImpl.init();

  /**
   * The meta object id for the '{@link xtext.factoryLang.shortDSL.shortDSL.impl.ModelImpl <em>Model</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see xtext.factoryLang.shortDSL.shortDSL.impl.ModelImpl
   * @see xtext.factoryLang.shortDSL.shortDSL.impl.ShortDSLPackageImpl#getModel()
   * @generated
   */
  int MODEL = 0;

  /**
   * The feature id for the '<em><b>Type</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL__TYPE = 0;

  /**
   * The number of structural features of the '<em>Model</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link xtext.factoryLang.shortDSL.shortDSL.impl.DSLTypeImpl <em>DSL Type</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see xtext.factoryLang.shortDSL.shortDSL.impl.DSLTypeImpl
   * @see xtext.factoryLang.shortDSL.shortDSL.impl.ShortDSLPackageImpl#getDSLType()
   * @generated
   */
  int DSL_TYPE = 1;

  /**
   * The number of structural features of the '<em>DSL Type</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DSL_TYPE_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link xtext.factoryLang.shortDSL.shortDSL.impl.Configuration_ShortImpl <em>Configuration Short</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see xtext.factoryLang.shortDSL.shortDSL.impl.Configuration_ShortImpl
   * @see xtext.factoryLang.shortDSL.shortDSL.impl.ShortDSLPackageImpl#getConfiguration_Short()
   * @generated
   */
  int CONFIGURATION_SHORT = 2;

  /**
   * The feature id for the '<em><b>Devices</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONFIGURATION_SHORT__DEVICES = 0;

  /**
   * The number of structural features of the '<em>Configuration Short</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONFIGURATION_SHORT_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link xtext.factoryLang.shortDSL.shortDSL.impl.Device_ShortImpl <em>Device Short</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see xtext.factoryLang.shortDSL.shortDSL.impl.Device_ShortImpl
   * @see xtext.factoryLang.shortDSL.shortDSL.impl.ShortDSLPackageImpl#getDevice_Short()
   * @generated
   */
  int DEVICE_SHORT = 3;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DEVICE_SHORT__NAME = 0;

  /**
   * The number of structural features of the '<em>Device Short</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DEVICE_SHORT_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link xtext.factoryLang.shortDSL.shortDSL.impl.Crane_ShortImpl <em>Crane Short</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see xtext.factoryLang.shortDSL.shortDSL.impl.Crane_ShortImpl
   * @see xtext.factoryLang.shortDSL.shortDSL.impl.ShortDSLPackageImpl#getCrane_Short()
   * @generated
   */
  int CRANE_SHORT = 4;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CRANE_SHORT__NAME = DEVICE_SHORT__NAME;

  /**
   * The feature id for the '<em><b>Positions</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CRANE_SHORT__POSITIONS = DEVICE_SHORT_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Crane Short</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CRANE_SHORT_FEATURE_COUNT = DEVICE_SHORT_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link xtext.factoryLang.shortDSL.shortDSL.impl.CranePosition_ShortImpl <em>Crane Position Short</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see xtext.factoryLang.shortDSL.shortDSL.impl.CranePosition_ShortImpl
   * @see xtext.factoryLang.shortDSL.shortDSL.impl.ShortDSLPackageImpl#getCranePosition_Short()
   * @generated
   */
  int CRANE_POSITION_SHORT = 5;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CRANE_POSITION_SHORT__NAME = 0;

  /**
   * The feature id for the '<em><b>Position</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CRANE_POSITION_SHORT__POSITION = 1;

  /**
   * The number of structural features of the '<em>Crane Position Short</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CRANE_POSITION_SHORT_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link xtext.factoryLang.shortDSL.shortDSL.impl.Disk_ShortImpl <em>Disk Short</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see xtext.factoryLang.shortDSL.shortDSL.impl.Disk_ShortImpl
   * @see xtext.factoryLang.shortDSL.shortDSL.impl.ShortDSLPackageImpl#getDisk_Short()
   * @generated
   */
  int DISK_SHORT = 6;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DISK_SHORT__NAME = DEVICE_SHORT__NAME;

  /**
   * The feature id for the '<em><b>NSlots</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DISK_SHORT__NSLOTS = DEVICE_SHORT_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Zones</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DISK_SHORT__ZONES = DEVICE_SHORT_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Disk Short</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DISK_SHORT_FEATURE_COUNT = DEVICE_SHORT_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link xtext.factoryLang.shortDSL.shortDSL.impl.DiskZone_ShortImpl <em>Disk Zone Short</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see xtext.factoryLang.shortDSL.shortDSL.impl.DiskZone_ShortImpl
   * @see xtext.factoryLang.shortDSL.shortDSL.impl.ShortDSLPackageImpl#getDiskZone_Short()
   * @generated
   */
  int DISK_ZONE_SHORT = 7;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DISK_ZONE_SHORT__NAME = 0;

  /**
   * The feature id for the '<em><b>Slot</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DISK_ZONE_SHORT__SLOT = 1;

  /**
   * The number of structural features of the '<em>Disk Zone Short</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DISK_ZONE_SHORT_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link xtext.factoryLang.shortDSL.shortDSL.impl.Camera_ShortImpl <em>Camera Short</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see xtext.factoryLang.shortDSL.shortDSL.impl.Camera_ShortImpl
   * @see xtext.factoryLang.shortDSL.shortDSL.impl.ShortDSLPackageImpl#getCamera_Short()
   * @generated
   */
  int CAMERA_SHORT = 8;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CAMERA_SHORT__NAME = DEVICE_SHORT__NAME;

  /**
   * The feature id for the '<em><b>Colors</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CAMERA_SHORT__COLORS = DEVICE_SHORT_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Camera Short</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CAMERA_SHORT_FEATURE_COUNT = DEVICE_SHORT_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link xtext.factoryLang.shortDSL.shortDSL.impl.CameraColor_ShortImpl <em>Camera Color Short</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see xtext.factoryLang.shortDSL.shortDSL.impl.CameraColor_ShortImpl
   * @see xtext.factoryLang.shortDSL.shortDSL.impl.ShortDSLPackageImpl#getCameraColor_Short()
   * @generated
   */
  int CAMERA_COLOR_SHORT = 9;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CAMERA_COLOR_SHORT__NAME = 0;

  /**
   * The number of structural features of the '<em>Camera Color Short</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CAMERA_COLOR_SHORT_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link xtext.factoryLang.shortDSL.shortDSL.impl.DeviceHandling_ShortImpl <em>Device Handling Short</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see xtext.factoryLang.shortDSL.shortDSL.impl.DeviceHandling_ShortImpl
   * @see xtext.factoryLang.shortDSL.shortDSL.impl.ShortDSLPackageImpl#getDeviceHandling_Short()
   * @generated
   */
  int DEVICE_HANDLING_SHORT = 10;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DEVICE_HANDLING_SHORT__NAME = 0;

  /**
   * The number of structural features of the '<em>Device Handling Short</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DEVICE_HANDLING_SHORT_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link xtext.factoryLang.shortDSL.shortDSL.impl.DSLShortImpl <em>DSL Short</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see xtext.factoryLang.shortDSL.shortDSL.impl.DSLShortImpl
   * @see xtext.factoryLang.shortDSL.shortDSL.impl.ShortDSLPackageImpl#getDSLShort()
   * @generated
   */
  int DSL_SHORT = 11;

  /**
   * The feature id for the '<em><b>Configuration</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DSL_SHORT__CONFIGURATION = DSL_TYPE_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Device Handlings</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DSL_SHORT__DEVICE_HANDLINGS = DSL_TYPE_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>DSL Short</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DSL_SHORT_FEATURE_COUNT = DSL_TYPE_FEATURE_COUNT + 2;


  /**
   * Returns the meta object for class '{@link xtext.factoryLang.shortDSL.shortDSL.Model <em>Model</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Model</em>'.
   * @see xtext.factoryLang.shortDSL.shortDSL.Model
   * @generated
   */
  EClass getModel();

  /**
   * Returns the meta object for the containment reference '{@link xtext.factoryLang.shortDSL.shortDSL.Model#getType <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Type</em>'.
   * @see xtext.factoryLang.shortDSL.shortDSL.Model#getType()
   * @see #getModel()
   * @generated
   */
  EReference getModel_Type();

  /**
   * Returns the meta object for class '{@link xtext.factoryLang.shortDSL.shortDSL.DSLType <em>DSL Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>DSL Type</em>'.
   * @see xtext.factoryLang.shortDSL.shortDSL.DSLType
   * @generated
   */
  EClass getDSLType();

  /**
   * Returns the meta object for class '{@link xtext.factoryLang.shortDSL.shortDSL.Configuration_Short <em>Configuration Short</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Configuration Short</em>'.
   * @see xtext.factoryLang.shortDSL.shortDSL.Configuration_Short
   * @generated
   */
  EClass getConfiguration_Short();

  /**
   * Returns the meta object for the containment reference list '{@link xtext.factoryLang.shortDSL.shortDSL.Configuration_Short#getDevices <em>Devices</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Devices</em>'.
   * @see xtext.factoryLang.shortDSL.shortDSL.Configuration_Short#getDevices()
   * @see #getConfiguration_Short()
   * @generated
   */
  EReference getConfiguration_Short_Devices();

  /**
   * Returns the meta object for class '{@link xtext.factoryLang.shortDSL.shortDSL.Device_Short <em>Device Short</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Device Short</em>'.
   * @see xtext.factoryLang.shortDSL.shortDSL.Device_Short
   * @generated
   */
  EClass getDevice_Short();

  /**
   * Returns the meta object for the attribute '{@link xtext.factoryLang.shortDSL.shortDSL.Device_Short#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see xtext.factoryLang.shortDSL.shortDSL.Device_Short#getName()
   * @see #getDevice_Short()
   * @generated
   */
  EAttribute getDevice_Short_Name();

  /**
   * Returns the meta object for class '{@link xtext.factoryLang.shortDSL.shortDSL.Crane_Short <em>Crane Short</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Crane Short</em>'.
   * @see xtext.factoryLang.shortDSL.shortDSL.Crane_Short
   * @generated
   */
  EClass getCrane_Short();

  /**
   * Returns the meta object for the containment reference list '{@link xtext.factoryLang.shortDSL.shortDSL.Crane_Short#getPositions <em>Positions</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Positions</em>'.
   * @see xtext.factoryLang.shortDSL.shortDSL.Crane_Short#getPositions()
   * @see #getCrane_Short()
   * @generated
   */
  EReference getCrane_Short_Positions();

  /**
   * Returns the meta object for class '{@link xtext.factoryLang.shortDSL.shortDSL.CranePosition_Short <em>Crane Position Short</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Crane Position Short</em>'.
   * @see xtext.factoryLang.shortDSL.shortDSL.CranePosition_Short
   * @generated
   */
  EClass getCranePosition_Short();

  /**
   * Returns the meta object for the attribute '{@link xtext.factoryLang.shortDSL.shortDSL.CranePosition_Short#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see xtext.factoryLang.shortDSL.shortDSL.CranePosition_Short#getName()
   * @see #getCranePosition_Short()
   * @generated
   */
  EAttribute getCranePosition_Short_Name();

  /**
   * Returns the meta object for the attribute '{@link xtext.factoryLang.shortDSL.shortDSL.CranePosition_Short#getPosition <em>Position</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Position</em>'.
   * @see xtext.factoryLang.shortDSL.shortDSL.CranePosition_Short#getPosition()
   * @see #getCranePosition_Short()
   * @generated
   */
  EAttribute getCranePosition_Short_Position();

  /**
   * Returns the meta object for class '{@link xtext.factoryLang.shortDSL.shortDSL.Disk_Short <em>Disk Short</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Disk Short</em>'.
   * @see xtext.factoryLang.shortDSL.shortDSL.Disk_Short
   * @generated
   */
  EClass getDisk_Short();

  /**
   * Returns the meta object for the attribute '{@link xtext.factoryLang.shortDSL.shortDSL.Disk_Short#getNSlots <em>NSlots</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>NSlots</em>'.
   * @see xtext.factoryLang.shortDSL.shortDSL.Disk_Short#getNSlots()
   * @see #getDisk_Short()
   * @generated
   */
  EAttribute getDisk_Short_NSlots();

  /**
   * Returns the meta object for the containment reference list '{@link xtext.factoryLang.shortDSL.shortDSL.Disk_Short#getZones <em>Zones</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Zones</em>'.
   * @see xtext.factoryLang.shortDSL.shortDSL.Disk_Short#getZones()
   * @see #getDisk_Short()
   * @generated
   */
  EReference getDisk_Short_Zones();

  /**
   * Returns the meta object for class '{@link xtext.factoryLang.shortDSL.shortDSL.DiskZone_Short <em>Disk Zone Short</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Disk Zone Short</em>'.
   * @see xtext.factoryLang.shortDSL.shortDSL.DiskZone_Short
   * @generated
   */
  EClass getDiskZone_Short();

  /**
   * Returns the meta object for the attribute '{@link xtext.factoryLang.shortDSL.shortDSL.DiskZone_Short#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see xtext.factoryLang.shortDSL.shortDSL.DiskZone_Short#getName()
   * @see #getDiskZone_Short()
   * @generated
   */
  EAttribute getDiskZone_Short_Name();

  /**
   * Returns the meta object for the attribute '{@link xtext.factoryLang.shortDSL.shortDSL.DiskZone_Short#getSlot <em>Slot</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Slot</em>'.
   * @see xtext.factoryLang.shortDSL.shortDSL.DiskZone_Short#getSlot()
   * @see #getDiskZone_Short()
   * @generated
   */
  EAttribute getDiskZone_Short_Slot();

  /**
   * Returns the meta object for class '{@link xtext.factoryLang.shortDSL.shortDSL.Camera_Short <em>Camera Short</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Camera Short</em>'.
   * @see xtext.factoryLang.shortDSL.shortDSL.Camera_Short
   * @generated
   */
  EClass getCamera_Short();

  /**
   * Returns the meta object for the containment reference list '{@link xtext.factoryLang.shortDSL.shortDSL.Camera_Short#getColors <em>Colors</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Colors</em>'.
   * @see xtext.factoryLang.shortDSL.shortDSL.Camera_Short#getColors()
   * @see #getCamera_Short()
   * @generated
   */
  EReference getCamera_Short_Colors();

  /**
   * Returns the meta object for class '{@link xtext.factoryLang.shortDSL.shortDSL.CameraColor_Short <em>Camera Color Short</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Camera Color Short</em>'.
   * @see xtext.factoryLang.shortDSL.shortDSL.CameraColor_Short
   * @generated
   */
  EClass getCameraColor_Short();

  /**
   * Returns the meta object for the attribute '{@link xtext.factoryLang.shortDSL.shortDSL.CameraColor_Short#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see xtext.factoryLang.shortDSL.shortDSL.CameraColor_Short#getName()
   * @see #getCameraColor_Short()
   * @generated
   */
  EAttribute getCameraColor_Short_Name();

  /**
   * Returns the meta object for class '{@link xtext.factoryLang.shortDSL.shortDSL.DeviceHandling_Short <em>Device Handling Short</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Device Handling Short</em>'.
   * @see xtext.factoryLang.shortDSL.shortDSL.DeviceHandling_Short
   * @generated
   */
  EClass getDeviceHandling_Short();

  /**
   * Returns the meta object for the attribute '{@link xtext.factoryLang.shortDSL.shortDSL.DeviceHandling_Short#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see xtext.factoryLang.shortDSL.shortDSL.DeviceHandling_Short#getName()
   * @see #getDeviceHandling_Short()
   * @generated
   */
  EAttribute getDeviceHandling_Short_Name();

  /**
   * Returns the meta object for class '{@link xtext.factoryLang.shortDSL.shortDSL.DSLShort <em>DSL Short</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>DSL Short</em>'.
   * @see xtext.factoryLang.shortDSL.shortDSL.DSLShort
   * @generated
   */
  EClass getDSLShort();

  /**
   * Returns the meta object for the containment reference '{@link xtext.factoryLang.shortDSL.shortDSL.DSLShort#getConfiguration <em>Configuration</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Configuration</em>'.
   * @see xtext.factoryLang.shortDSL.shortDSL.DSLShort#getConfiguration()
   * @see #getDSLShort()
   * @generated
   */
  EReference getDSLShort_Configuration();

  /**
   * Returns the meta object for the containment reference list '{@link xtext.factoryLang.shortDSL.shortDSL.DSLShort#getDeviceHandlings <em>Device Handlings</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Device Handlings</em>'.
   * @see xtext.factoryLang.shortDSL.shortDSL.DSLShort#getDeviceHandlings()
   * @see #getDSLShort()
   * @generated
   */
  EReference getDSLShort_DeviceHandlings();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  ShortDSLFactory getShortDSLFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link xtext.factoryLang.shortDSL.shortDSL.impl.ModelImpl <em>Model</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see xtext.factoryLang.shortDSL.shortDSL.impl.ModelImpl
     * @see xtext.factoryLang.shortDSL.shortDSL.impl.ShortDSLPackageImpl#getModel()
     * @generated
     */
    EClass MODEL = eINSTANCE.getModel();

    /**
     * The meta object literal for the '<em><b>Type</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MODEL__TYPE = eINSTANCE.getModel_Type();

    /**
     * The meta object literal for the '{@link xtext.factoryLang.shortDSL.shortDSL.impl.DSLTypeImpl <em>DSL Type</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see xtext.factoryLang.shortDSL.shortDSL.impl.DSLTypeImpl
     * @see xtext.factoryLang.shortDSL.shortDSL.impl.ShortDSLPackageImpl#getDSLType()
     * @generated
     */
    EClass DSL_TYPE = eINSTANCE.getDSLType();

    /**
     * The meta object literal for the '{@link xtext.factoryLang.shortDSL.shortDSL.impl.Configuration_ShortImpl <em>Configuration Short</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see xtext.factoryLang.shortDSL.shortDSL.impl.Configuration_ShortImpl
     * @see xtext.factoryLang.shortDSL.shortDSL.impl.ShortDSLPackageImpl#getConfiguration_Short()
     * @generated
     */
    EClass CONFIGURATION_SHORT = eINSTANCE.getConfiguration_Short();

    /**
     * The meta object literal for the '<em><b>Devices</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CONFIGURATION_SHORT__DEVICES = eINSTANCE.getConfiguration_Short_Devices();

    /**
     * The meta object literal for the '{@link xtext.factoryLang.shortDSL.shortDSL.impl.Device_ShortImpl <em>Device Short</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see xtext.factoryLang.shortDSL.shortDSL.impl.Device_ShortImpl
     * @see xtext.factoryLang.shortDSL.shortDSL.impl.ShortDSLPackageImpl#getDevice_Short()
     * @generated
     */
    EClass DEVICE_SHORT = eINSTANCE.getDevice_Short();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DEVICE_SHORT__NAME = eINSTANCE.getDevice_Short_Name();

    /**
     * The meta object literal for the '{@link xtext.factoryLang.shortDSL.shortDSL.impl.Crane_ShortImpl <em>Crane Short</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see xtext.factoryLang.shortDSL.shortDSL.impl.Crane_ShortImpl
     * @see xtext.factoryLang.shortDSL.shortDSL.impl.ShortDSLPackageImpl#getCrane_Short()
     * @generated
     */
    EClass CRANE_SHORT = eINSTANCE.getCrane_Short();

    /**
     * The meta object literal for the '<em><b>Positions</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CRANE_SHORT__POSITIONS = eINSTANCE.getCrane_Short_Positions();

    /**
     * The meta object literal for the '{@link xtext.factoryLang.shortDSL.shortDSL.impl.CranePosition_ShortImpl <em>Crane Position Short</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see xtext.factoryLang.shortDSL.shortDSL.impl.CranePosition_ShortImpl
     * @see xtext.factoryLang.shortDSL.shortDSL.impl.ShortDSLPackageImpl#getCranePosition_Short()
     * @generated
     */
    EClass CRANE_POSITION_SHORT = eINSTANCE.getCranePosition_Short();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CRANE_POSITION_SHORT__NAME = eINSTANCE.getCranePosition_Short_Name();

    /**
     * The meta object literal for the '<em><b>Position</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CRANE_POSITION_SHORT__POSITION = eINSTANCE.getCranePosition_Short_Position();

    /**
     * The meta object literal for the '{@link xtext.factoryLang.shortDSL.shortDSL.impl.Disk_ShortImpl <em>Disk Short</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see xtext.factoryLang.shortDSL.shortDSL.impl.Disk_ShortImpl
     * @see xtext.factoryLang.shortDSL.shortDSL.impl.ShortDSLPackageImpl#getDisk_Short()
     * @generated
     */
    EClass DISK_SHORT = eINSTANCE.getDisk_Short();

    /**
     * The meta object literal for the '<em><b>NSlots</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DISK_SHORT__NSLOTS = eINSTANCE.getDisk_Short_NSlots();

    /**
     * The meta object literal for the '<em><b>Zones</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DISK_SHORT__ZONES = eINSTANCE.getDisk_Short_Zones();

    /**
     * The meta object literal for the '{@link xtext.factoryLang.shortDSL.shortDSL.impl.DiskZone_ShortImpl <em>Disk Zone Short</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see xtext.factoryLang.shortDSL.shortDSL.impl.DiskZone_ShortImpl
     * @see xtext.factoryLang.shortDSL.shortDSL.impl.ShortDSLPackageImpl#getDiskZone_Short()
     * @generated
     */
    EClass DISK_ZONE_SHORT = eINSTANCE.getDiskZone_Short();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DISK_ZONE_SHORT__NAME = eINSTANCE.getDiskZone_Short_Name();

    /**
     * The meta object literal for the '<em><b>Slot</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DISK_ZONE_SHORT__SLOT = eINSTANCE.getDiskZone_Short_Slot();

    /**
     * The meta object literal for the '{@link xtext.factoryLang.shortDSL.shortDSL.impl.Camera_ShortImpl <em>Camera Short</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see xtext.factoryLang.shortDSL.shortDSL.impl.Camera_ShortImpl
     * @see xtext.factoryLang.shortDSL.shortDSL.impl.ShortDSLPackageImpl#getCamera_Short()
     * @generated
     */
    EClass CAMERA_SHORT = eINSTANCE.getCamera_Short();

    /**
     * The meta object literal for the '<em><b>Colors</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CAMERA_SHORT__COLORS = eINSTANCE.getCamera_Short_Colors();

    /**
     * The meta object literal for the '{@link xtext.factoryLang.shortDSL.shortDSL.impl.CameraColor_ShortImpl <em>Camera Color Short</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see xtext.factoryLang.shortDSL.shortDSL.impl.CameraColor_ShortImpl
     * @see xtext.factoryLang.shortDSL.shortDSL.impl.ShortDSLPackageImpl#getCameraColor_Short()
     * @generated
     */
    EClass CAMERA_COLOR_SHORT = eINSTANCE.getCameraColor_Short();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CAMERA_COLOR_SHORT__NAME = eINSTANCE.getCameraColor_Short_Name();

    /**
     * The meta object literal for the '{@link xtext.factoryLang.shortDSL.shortDSL.impl.DeviceHandling_ShortImpl <em>Device Handling Short</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see xtext.factoryLang.shortDSL.shortDSL.impl.DeviceHandling_ShortImpl
     * @see xtext.factoryLang.shortDSL.shortDSL.impl.ShortDSLPackageImpl#getDeviceHandling_Short()
     * @generated
     */
    EClass DEVICE_HANDLING_SHORT = eINSTANCE.getDeviceHandling_Short();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DEVICE_HANDLING_SHORT__NAME = eINSTANCE.getDeviceHandling_Short_Name();

    /**
     * The meta object literal for the '{@link xtext.factoryLang.shortDSL.shortDSL.impl.DSLShortImpl <em>DSL Short</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see xtext.factoryLang.shortDSL.shortDSL.impl.DSLShortImpl
     * @see xtext.factoryLang.shortDSL.shortDSL.impl.ShortDSLPackageImpl#getDSLShort()
     * @generated
     */
    EClass DSL_SHORT = eINSTANCE.getDSLShort();

    /**
     * The meta object literal for the '<em><b>Configuration</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DSL_SHORT__CONFIGURATION = eINSTANCE.getDSLShort_Configuration();

    /**
     * The meta object literal for the '<em><b>Device Handlings</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DSL_SHORT__DEVICE_HANDLINGS = eINSTANCE.getDSLShort_DeviceHandlings();

  }

} //ShortDSLPackage
