/**
 * generated by Xtext 2.25.0
 */
package xtext.factoryLang.shortDSL.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import xtext.factoryLang.shortDSL.ShortDSLRuntimeModule;
import xtext.factoryLang.shortDSL.ShortDSLStandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class ShortDSLIdeSetup extends ShortDSLStandaloneSetup {
  @Override
  public Injector createInjector() {
    ShortDSLRuntimeModule _shortDSLRuntimeModule = new ShortDSLRuntimeModule();
    ShortDSLIdeModule _shortDSLIdeModule = new ShortDSLIdeModule();
    return Guice.createInjector(Modules2.mixin(_shortDSLRuntimeModule, _shortDSLIdeModule));
  }
}
