/*
 * generated by Xtext 2.25.0
 */
package xtext.factoryLang.parser.antlr;

import org.antlr.runtime.Token;
import org.antlr.runtime.TokenSource;
import org.eclipse.xtext.parser.antlr.AbstractIndentationTokenSource;
import xtext.factoryLang.parser.antlr.internal.InternalFactoryLangLongParser;

public class FactoryLangLongTokenSource extends AbstractIndentationTokenSource {

	public FactoryLangLongTokenSource(TokenSource delegate) {
		super(delegate);
	}

	@Override
	protected boolean shouldSplitTokenImpl(Token token) {
		// TODO Review assumption
		return token.getType() == InternalFactoryLangLongParser.RULE_WS;
	}

	@Override
	protected int getBeginTokenType() {
		// TODO Review assumption
		return InternalFactoryLangLongParser.RULE_BEGIN;
	}

	@Override
	protected int getEndTokenType() {
		// TODO Review assumption
		return InternalFactoryLangLongParser.RULE_END;
	}

}
